class AddTypSubcategories < ActiveRecord::Migration
  def up
  	#Typ_subcategories
  	TypSubcategory.create(id: 1, typ_category_id: 1, name: "Bread")
  	TypSubcategory.create(id: 2, typ_category_id: 1, name: "Bun")
  	TypSubcategory.create(id: 3, typ_category_id: 1, name: "Cakes & Pastries")
  	TypSubcategory.create(id: 4, typ_category_id: 1, name: "Gluten Free Products")
  	TypSubcategory.create(id: 5, typ_category_id: 2, name: "Cheeses")
  	TypSubcategory.create(id: 6, typ_category_id: 2, name: "Meats")
  	TypSubcategory.create(id: 7, typ_category_id: 2, name: "Salads")
  	TypSubcategory.create(id: 8, typ_category_id: 2, name: "Specialty Items")
  	TypSubcategory.create(id: 9, typ_category_id: 3, name: "Candy & Gifts")
  	TypSubcategory.create(id: 10, typ_category_id: 3, name: "Flowers")
  	TypSubcategory.create(id: 11, typ_category_id: 4, name: "Baking")
  	TypSubcategory.create(id: 12, typ_category_id: 4, name: "Beverages")
  	TypSubcategory.create(id: 13, typ_category_id: 4, name: "Bulk Foods")
  	TypSubcategory.create(id: 14, typ_category_id: 4, name: "Canned Foods")
  	TypSubcategory.create(id: 15, typ_category_id: 4, name: "Cereals")
  	TypSubcategory.create(id: 16, typ_category_id: 4, name: "Condiments")
  	TypSubcategory.create(id: 17, typ_category_id: 4, name: "Cookies & Crackers")
  	TypSubcategory.create(id: 18, typ_category_id: 4, name: "Dairy")
  	TypSubcategory.create(id: 19, typ_category_id: 4, name: "Dairy/Meat Alternatives")
  	TypSubcategory.create(id: 20, typ_category_id: 4, name: "Ethnic Foods")
  	TypSubcategory.create(id: 21, typ_category_id: 4, name: "Frozen")
  	TypSubcategory.create(id: 22, typ_category_id: 4, name: "Pasta, Rice, & Potato")
  	TypSubcategory.create(id: 23, typ_category_id: 4, name: "Seasonings")
  	TypSubcategory.create(id: 24, typ_category_id: 4, name: "Snacks")
  	TypSubcategory.create(id: 25, typ_category_id: 4, name: "Soups")
  	TypSubcategory.create(id: 26, typ_category_id: 4, name: "Spreads, Syrups, & Toppings")
  	TypSubcategory.create(id: 27, typ_category_id: 5, name: "Meat & Serve")
  	TypSubcategory.create(id: 28, typ_category_id: 5, name: "Oven Ready")
  	TypSubcategory.create(id: 29, typ_category_id: 5, name: "Ready to Eat")
  	TypSubcategory.create(id: 30, typ_category_id: 6, name: "Bacon & Ham")
  	TypSubcategory.create(id: 31, typ_category_id: 6, name: "Beef")
  	TypSubcategory.create(id: 32, typ_category_id: 6, name: "Lamb, Veal, & Bison")
  	TypSubcategory.create(id: 33, typ_category_id: 6, name: "Pork")
  	TypSubcategory.create(id: 34, typ_category_id: 6, name: "Poultry")
  	TypSubcategory.create(id: 35, typ_category_id: 6, name: "Processed")
  	TypSubcategory.create(id: 36, typ_category_id: 7, name: "Deli")
  	TypSubcategory.create(id: 37, typ_category_id: 7, name: "Grocery")
  	TypSubcategory.create(id: 38, typ_category_id: 7, name: "Produce")
  	TypSubcategory.create(id: 39, typ_category_id: 8, name: "Bakery Trays")
  	TypSubcategory.create(id: 40, typ_category_id: 8, name: "Deli Trays")
  	TypSubcategory.create(id: 41, typ_category_id: 8, name: "Seafood Trays")
  	TypSubcategory.create(id: 42, typ_category_id: 8, name: "Sushi Trays")
  	TypSubcategory.create(id: 43, typ_category_id: 9, name: "Fruits")
  	TypSubcategory.create(id: 44, typ_category_id: 9, name: "Juice")
  	TypSubcategory.create(id: 45, typ_category_id: 9, name: "Packaged Salads")
  	TypSubcategory.create(id: 46, typ_category_id: 9, name: "Vegetables")
  	TypSubcategory.create(id: 47, typ_category_id: 10, name: "Fillets")
  	TypSubcategory.create(id: 48, typ_category_id: 10, name: "Prawns & Shrimp")
  	TypSubcategory.create(id: 49, typ_category_id: 10, name: "Salmon")
  	TypSubcategory.create(id: 50, typ_category_id: 10, name: "Shellfish")
  	TypSubcategory.create(id: 51, typ_category_id: 10, name: "Specialty Items")
  end
end
